repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
        files: ^(src|tests)/.*\.py$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args:
            - --ignore-missing-imports
            - --strict
            - --install-types
            - --non-interactive
        files: ^(src|tests)/.*\.py$
-   repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
    -   id: flake8
        files: ^src/.*\.py$
        args:
          - --max-line-length=88
          - --ignore=E203,W503
